package dakt.javatech.jhibernate.entity;
// Generated Sep 26, 2018 6:04:22 AM by Hibernate Tools 5.3.1.Final

/**
 * Cmtgrammar generated by hbm2java
 */
public class Cmtgrammar implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer cmtgrammarid;
	private Grammarguideline grammarguideline;
	private Member member;
	private String cmtgrammarcontent;

	public Cmtgrammar() {
	}

	public Cmtgrammar(Grammarguideline grammarguideline, Member member, String cmtgrammarcontent) {
		this.grammarguideline = grammarguideline;
		this.member = member;
		this.cmtgrammarcontent = cmtgrammarcontent;
	}

	public Integer getCmtgrammarid() {
		return this.cmtgrammarid;
	}

	public void setCmtgrammarid(Integer cmtgrammarid) {
		this.cmtgrammarid = cmtgrammarid;
	}

	public Grammarguideline getGrammarguideline() {
		return this.grammarguideline;
	}

	public void setGrammarguideline(Grammarguideline grammarguideline) {
		this.grammarguideline = grammarguideline;
	}

	public Member getMember() {
		return this.member;
	}

	public void setMember(Member member) {
		this.member = member;
	}

	public String getCmtgrammarcontent() {
		return this.cmtgrammarcontent;
	}

	public void setCmtgrammarcontent(String cmtgrammarcontent) {
		this.cmtgrammarcontent = cmtgrammarcontent;
	}

}
