package dakt.javatech.jhibernate.entity;
// Generated Sep 26, 2018 6:04:22 AM by Hibernate Tools 5.3.1.Final

/**
 * Cmtvocabulary generated by hbm2java
 */
public class Cmtvocabulary implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer cmtvocabularyid;
	private Member member;
	private Vocabularyguideline vocabularyguideline;
	private String cmtvocabularycontent;

	public Cmtvocabulary() {
	}

	public Cmtvocabulary(Member member, Vocabularyguideline vocabularyguideline, String cmtvocabularycontent) {
		this.member = member;
		this.vocabularyguideline = vocabularyguideline;
		this.cmtvocabularycontent = cmtvocabularycontent;
	}

	public Integer getCmtvocabularyid() {
		return this.cmtvocabularyid;
	}

	public void setCmtvocabularyid(Integer cmtvocabularyid) {
		this.cmtvocabularyid = cmtvocabularyid;
	}

	public Member getMember() {
		return this.member;
	}

	public void setMember(Member member) {
		this.member = member;
	}

	public Vocabularyguideline getVocabularyguideline() {
		return this.vocabularyguideline;
	}

	public void setVocabularyguideline(Vocabularyguideline vocabularyguideline) {
		this.vocabularyguideline = vocabularyguideline;
	}

	public String getCmtvocabularycontent() {
		return this.cmtvocabularycontent;
	}

	public void setCmtvocabularycontent(String cmtvocabularycontent) {
		this.cmtvocabularycontent = cmtvocabularycontent;
	}

}
