package dakt.javatech.jhibernate.entity;
// Generated Sep 26, 2018 6:04:22 AM by Hibernate Tools 5.3.1.Final

import java.util.Set;

import org.codehaus.jackson.annotate.JsonBackReference;

/**
 * Examination generated by hbm2java
 */
public class Examination implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer examinationid;
	private String examinationame;
	private String examinatioimage;
	private Integer checkedcauhoi;

	public Examination() {
	}
//
//	public Examination(String examinationame, String examinatioimage, Integer checkedcauhoi, Set results,
//			Set examinationquestions) {
//		this.examinationame = examinationame;
//		this.examinatioimage = examinatioimage;
//		this.checkedcauhoi = checkedcauhoi;
//		this.results = results;
//		this.examinationquestions = examinationquestions;
//	}

	public Integer getExaminationid() {
		return this.examinationid;
	}

	public void setExaminationid(Integer examinationid) {
		this.examinationid = examinationid;
	}

	public String getExaminationame() {
		return this.examinationame;
	}

	public void setExaminationame(String examinationame) {
		this.examinationame = examinationame;
	}

	public String getExaminatioimage() {
		return this.examinatioimage;
	}

	public void setExaminatioimage(String examinatioimage) {
		this.examinatioimage = examinatioimage;
	}

	public Integer getCheckedcauhoi() {
		return this.checkedcauhoi;
	}

	public void setCheckedcauhoi(Integer checkedcauhoi) {
		this.checkedcauhoi = checkedcauhoi;
	}

}
