package dakt.javatech.jhibernate.entity;
// Generated Sep 26, 2018 6:04:22 AM by Hibernate Tools 5.3.1.Final

/**
 * Examinationquestion generated by hbm2java
 */
public class Examinationquestion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer examinationquestionid;
	private Integer examinationid;
	private Integer num;
	private String imagequestion;
	private String audiogg;
	private String audiomp3;
	private String paragraph;
	private String question;
	private String option1;
	private String option2;
	private String option3;
	private String option4;
	private String correctanswer;

	public Examinationquestion() {
	}

//	public Examinationquestion(Examination examination, Integer num, String imagequestion, String audiogg,
//			String audiomp3, String paragraph, String question, String option1, String option2, String option3,
//			String option4, String correctanswer) {
//		this.examination = examination;
//		this.num = num;
//		this.imagequestion = imagequestion;
//		this.audiogg = audiogg;
//		this.audiomp3 = audiomp3;
//		this.paragraph = paragraph;
//		this.question = question;
//		this.option1 = option1;
//		this.option2 = option2;
//		this.option3 = option3;
//		this.option4 = option4;
//		this.correctanswer = correctanswer;
//	}

	public Integer getExaminationquestionid() {
		return this.examinationquestionid;
	}

	public void setExaminationquestionid(Integer examinationquestionid) {
		this.examinationquestionid = examinationquestionid;
	}

	public Integer getNum() {
		return this.num;
	}

	public void setNum(Integer num) {
		this.num = num;
	}

	public String getImagequestion() {
		return this.imagequestion;
	}

	public void setImagequestion(String imagequestion) {
		this.imagequestion = imagequestion;
	}

	public String getAudiogg() {
		return this.audiogg;
	}

	public void setAudiogg(String audiogg) {
		this.audiogg = audiogg;
	}

	public String getAudiomp3() {
		return this.audiomp3;
	}

	public void setAudiomp3(String audiomp3) {
		this.audiomp3 = audiomp3;
	}

	public String getParagraph() {
		return this.paragraph;
	}

	public void setParagraph(String paragraph) {
		this.paragraph = paragraph;
	}

	public String getQuestion() {
		return this.question;
	}

	public void setQuestion(String question) {
		this.question = question;
	}

	public String getOption1() {
		return this.option1;
	}

	public void setOption1(String option1) {
		this.option1 = option1;
	}

	public String getOption2() {
		return this.option2;
	}

	public void setOption2(String option2) {
		this.option2 = option2;
	}

	public String getOption3() {
		return this.option3;
	}

	public void setOption3(String option3) {
		this.option3 = option3;
	}

	public String getOption4() {
		return this.option4;
	}

	public void setOption4(String option4) {
		this.option4 = option4;
	}

	public String getCorrectanswer() {
		return this.correctanswer;
	}

	public void setCorrectanswer(String correctanswer) {
		this.correctanswer = correctanswer;
	}

	public Integer getExaminationid() {
		return examinationid;
	}

	public void setExaminationid(Integer examinationid) {
		this.examinationid = examinationid;
	}

}
