package dakt.javatech.jhibernate.entity;
// Generated Sep 26, 2018 6:04:22 AM by Hibernate Tools 5.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Grammarguideline generated by hbm2java
 */
public class Grammarguideline implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer grammarguidelineid;
	private String grammarname;
	private String grammarimage;
	private String content;
	private Set<Cmtgrammar> cmtgrammars;

	public Grammarguideline() {
	}

//	public Grammarguideline(String grammarname, String grammarimage, String content, Set cmtgrammars) {
//		this.grammarname = grammarname;
//		this.grammarimage = grammarimage;
//		this.content = content;
//		this.cmtgrammars = cmtgrammars;
//	}

	public Integer getGrammarguidelineid() {
		return this.grammarguidelineid;
	}

	public void setGrammarguidelineid(Integer grammarguidelineid) {
		this.grammarguidelineid = grammarguidelineid;
	}

	public String getGrammarname() {
		return this.grammarname;
	}

	public void setGrammarname(String grammarname) {
		this.grammarname = grammarname;
	}

	public String getGrammarimage() {
		return this.grammarimage;
	}

	public void setGrammarimage(String grammarimage) {
		this.grammarimage = grammarimage;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Set getCmtgrammars() {
		return this.cmtgrammars;
	}

	public void setCmtgrammars(Set cmtgrammars) {
		this.cmtgrammars = cmtgrammars;
	}

}
