package dakt.javatech.jhibernate.entity;
// Generated Sep 26, 2018 6:04:22 AM by Hibernate Tools 5.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Listenexercise generated by hbm2java
 */
public class Listenexercise implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer listenexerciseid;
	private String listenexercisename;
	private String listenexerciseimage;
	private Integer checkcauhoi;
	private Set<Listenquestion> listenquestions;

	public Listenexercise() {
	}

//	public Listenexercise(String listenexercisename, String listenexerciseimage, Integer checkcauhoi,
//			Set listenquestions) {
//		this.listenexercisename = listenexercisename;
//		this.listenexerciseimage = listenexerciseimage;
//		this.checkcauhoi = checkcauhoi;
//		this.listenquestions = listenquestions;
//	}

	public Integer getListenexerciseid() {
		return this.listenexerciseid;
	}

	public void setListenexerciseid(Integer listenexerciseid) {
		this.listenexerciseid = listenexerciseid;
	}

	public String getListenexercisename() {
		return this.listenexercisename;
	}

	public void setListenexercisename(String listenexercisename) {
		this.listenexercisename = listenexercisename;
	}

	public String getListenexerciseimage() {
		return this.listenexerciseimage;
	}

	public void setListenexerciseimage(String listenexerciseimage) {
		this.listenexerciseimage = listenexerciseimage;
	}

	public Integer getCheckcauhoi() {
		return this.checkcauhoi;
	}

	public void setCheckcauhoi(Integer checkcauhoi) {
		this.checkcauhoi = checkcauhoi;
	}

	public Set getListenquestions() {
		return this.listenquestions;
	}

	public void setListenquestions(Set listenquestions) {
		this.listenquestions = listenquestions;
	}

}
