package dakt.javatech.jhibernate.entity;
// Generated Sep 26, 2018 6:04:22 AM by Hibernate Tools 5.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Member generated by hbm2java
 */
public class Member implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer memberid;
	private Categorymember categorymember;
	private String name;
	private String membername;
	private String memberpass;
	private Set results = new HashSet(0);
	private Set cmtvocabularies = new HashSet(0);
	private Set cmtgrammars = new HashSet(0);

	public Member() {
	}

	public Member(Categorymember categorymember, String name, String membername, String memberpass, Set results,
			Set cmtvocabularies, Set cmtgrammars) {
		this.categorymember = categorymember;
		this.name = name;
		this.membername = membername;
		this.memberpass = memberpass;
		this.results = results;
		this.cmtvocabularies = cmtvocabularies;
		this.cmtgrammars = cmtgrammars;
	}

	public Integer getMemberid() {
		return this.memberid;
	}

	public void setMemberid(Integer memberid) {
		this.memberid = memberid;
	}

	public Categorymember getCategorymember() {
		return this.categorymember;
	}

	public void setCategorymember(Categorymember categorymember) {
		this.categorymember = categorymember;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getMembername() {
		return this.membername;
	}

	public void setMembername(String membername) {
		this.membername = membername;
	}

	public String getMemberpass() {
		return this.memberpass;
	}

	public void setMemberpass(String memberpass) {
		this.memberpass = memberpass;
	}

	public Set getResults() {
		return this.results;
	}

	public void setResults(Set results) {
		this.results = results;
	}

	public Set getCmtvocabularies() {
		return this.cmtvocabularies;
	}

	public void setCmtvocabularies(Set cmtvocabularies) {
		this.cmtvocabularies = cmtvocabularies;
	}

	public Set getCmtgrammars() {
		return this.cmtgrammars;
	}

	public void setCmtgrammars(Set cmtgrammars) {
		this.cmtgrammars = cmtgrammars;
	}

}
