package dakt.javatech.jhibernate.entity;
// Generated Sep 26, 2018 6:04:22 AM by Hibernate Tools 5.3.1.Final

/**
 * Slidebanner generated by hbm2java
 */
public class Slidebanner implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int slidebannerid;
	private String slidename;
	private String slidecontent;
	private String slideimage;

	public Slidebanner() {
	}

	public Slidebanner(int slidebannerid) {
		this.slidebannerid = slidebannerid;
	}

	public Slidebanner(int slidebannerid, String slidename, String slidecontent, String slideimage) {
		this.slidebannerid = slidebannerid;
		this.slidename = slidename;
		this.slidecontent = slidecontent;
		this.slideimage = slideimage;
	}

	public int getSlidebannerid() {
		return this.slidebannerid;
	}

	public void setSlidebannerid(int slidebannerid) {
		this.slidebannerid = slidebannerid;
	}

	public String getSlidename() {
		return this.slidename;
	}

	public void setSlidename(String slidename) {
		this.slidename = slidename;
	}

	public String getSlidecontent() {
		return this.slidecontent;
	}

	public void setSlidecontent(String slidecontent) {
		this.slidecontent = slidecontent;
	}

	public String getSlideimage() {
		return this.slideimage;
	}

	public void setSlideimage(String slideimage) {
		this.slideimage = slideimage;
	}

}
