package dakt.javatech.jhibernate.entity;
// Generated Sep 26, 2018 6:04:22 AM by Hibernate Tools 5.3.1.Final

import java.util.HashSet;
import java.util.Set;

import org.codehaus.jackson.annotate.JsonBackReference;

/**
 * Vocabularyguideline generated by hbm2java
 */
public class Vocabularyguideline implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer vocabularyguidelineid;
	private String vocabularyname;
	private String vocabularyimage;
	private Integer checknoidung;
	private Integer levelid;

	public Vocabularyguideline() {
	}

	public Integer getVocabularyguidelineid() {
		return this.vocabularyguidelineid;
	}

	public void setVocabularyguidelineid(Integer vocabularyguidelineid) {
		this.vocabularyguidelineid = vocabularyguidelineid;
	}

	public String getVocabularyname() {
		return this.vocabularyname;
	}

	public void setVocabularyname(String vocabularyname) {
		this.vocabularyname = vocabularyname;
	}

	public String getVocabularyimage() {
		return this.vocabularyimage;
	}

	public void setVocabularyimage(String vocabularyimage) {
		this.vocabularyimage = vocabularyimage;
	}

	public Integer getChecknoidung() {
		return this.checknoidung;
	}

	public void setChecknoidung(Integer checknoidung) {
		this.checknoidung = checknoidung;
	}

	public Integer getLevelid() {
		return levelid;
	}

	public void setLevelid(Integer levelid) {
		this.levelid = levelid;
	}

}
