package dakt.javatech.jhibernate.entity;
// Generated Sep 26, 2018 6:04:22 AM by Hibernate Tools 5.3.1.Final

/**
 * Vocabularycontent generated by hbm2java
 */
public class Vocabularycontent implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer vocabularycontentid;
	private Vocabularyguideline vocabularyguideline;
	private Integer num;
	private String vocabularycontentname;
	private String transcribe;
	private String image;
	private String audiomp3;
	private String audiogg;
	private String mean;

	public Vocabularycontent() {
	}

	public Vocabularycontent(Vocabularyguideline vocabularyguideline, Integer num, String vocabularycontentname,
			String transcribe, String image, String audiomp3, String audiogg, String mean) {
		this.vocabularyguideline = vocabularyguideline;
		this.num = num;
		this.vocabularycontentname = vocabularycontentname;
		this.transcribe = transcribe;
		this.image = image;
		this.audiomp3 = audiomp3;
		this.audiogg = audiogg;
		this.mean = mean;
	}

	public Integer getVocabularycontentid() {
		return this.vocabularycontentid;
	}

	public void setVocabularycontentid(Integer vocabularycontentid) {
		this.vocabularycontentid = vocabularycontentid;
	}

	public Vocabularyguideline getVocabularyguideline() {
		return this.vocabularyguideline;
	}

	public void setVocabularyguideline(Vocabularyguideline vocabularyguideline) {
		this.vocabularyguideline = vocabularyguideline;
	}

	public Integer getNum() {
		return this.num;
	}

	public void setNum(Integer num) {
		this.num = num;
	}

	public String getVocabularycontentname() {
		return this.vocabularycontentname;
	}

	public void setVocabularycontentname(String vocabularycontentname) {
		this.vocabularycontentname = vocabularycontentname;
	}

	public String getTranscribe() {
		return this.transcribe;
	}

	public void setTranscribe(String transcribe) {
		this.transcribe = transcribe;
	}

	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	public String getAudiomp3() {
		return this.audiomp3;
	}

	public void setAudiomp3(String audiomp3) {
		this.audiomp3 = audiomp3;
	}

	public String getAudiogg() {
		return this.audiogg;
	}

	public void setAudiogg(String audiogg) {
		this.audiogg = audiogg;
	}

	public String getMean() {
		return this.mean;
	}

	public void setMean(String mean) {
		this.mean = mean;
	}

}
