package dakt.javatech.jhibernate.entity;
// Generated Sep 26, 2018 6:04:22 AM by Hibernate Tools 5.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Vocabularyguideline generated by hbm2java
 */
public class Vocabularyguideline implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer vocabularyguidelineid;
	private String vocabularyname;
	private String vocabularyimage;
	private Integer checknoidung;
	private Set cmtvocabularies = new HashSet(0);
	private Set vocabularycontents = new HashSet(0);

	public Vocabularyguideline() {
	}

	public Vocabularyguideline(String vocabularyname, String vocabularyimage, Integer checknoidung, Set cmtvocabularies,
			Set vocabularycontents) {
		this.vocabularyname = vocabularyname;
		this.vocabularyimage = vocabularyimage;
		this.checknoidung = checknoidung;
		this.cmtvocabularies = cmtvocabularies;
		this.vocabularycontents = vocabularycontents;
	}

	public Integer getVocabularyguidelineid() {
		return this.vocabularyguidelineid;
	}

	public void setVocabularyguidelineid(Integer vocabularyguidelineid) {
		this.vocabularyguidelineid = vocabularyguidelineid;
	}

	public String getVocabularyname() {
		return this.vocabularyname;
	}

	public void setVocabularyname(String vocabularyname) {
		this.vocabularyname = vocabularyname;
	}

	public String getVocabularyimage() {
		return this.vocabularyimage;
	}

	public void setVocabularyimage(String vocabularyimage) {
		this.vocabularyimage = vocabularyimage;
	}

	public Integer getChecknoidung() {
		return this.checknoidung;
	}

	public void setChecknoidung(Integer checknoidung) {
		this.checknoidung = checknoidung;
	}

	public Set getCmtvocabularies() {
		return this.cmtvocabularies;
	}

	public void setCmtvocabularies(Set cmtvocabularies) {
		this.cmtvocabularies = cmtvocabularies;
	}

	public Set getVocabularycontents() {
		return this.vocabularycontents;
	}

	public void setVocabularycontents(Set vocabularycontents) {
		this.vocabularycontents = vocabularycontents;
	}

}
